import homeRoutes from "./home.js";
import tutorialRoutes from "./tutorial.js";
import userRoutes from "./sa-user.js";
import menuRoutes from "./sa-menus.js";
import itemTypeRoutes from './bs-item-type.js';
import capacityRoutes from "./capacity.js";
import wareHouseRoutes from "./bs-warehouse.js";
import blockRoutes from "./bs-blocks.js";
import gateRoutes from "./bs-gates.js";
import equipmentTypeRoutes from "./bs-equipments-types.js";
import equipmentRoutes from "./bs-equipments.js";
import methodRoutes from "./bs-method.js";
import unitRoutes from "./bs-units.js";
import contractRoutes from "./bs-contracts.js";
import customerRoutes from "./bs-customer.js";
import customerTypeRoutes from "./bs-customer-type.js";
import truckRoutes from "./bs-trucks.js";
import romoocRoutes from "./bs-romooc.js";
import contractBlockRoutes from './bs-contract-blocks.js';
import vesselVisitRoutes from './dt-vessel-visits.js';
import maniFestCNTRRoutes from './dt-cntr-mnf-ld.js';
import cntrStockRoutes from './dt-cntr-stocks.js';
import pkgManifestladingRoutes from './dt-package-mnf-ld.js';
import tfrCodeRoutes from './trf-codes.js';
import tfrStdRoutes from './trf-stds.js';
import accountRoutes from './accounts.js';
import currentTypeRoutes from './currency-type.js';
import configAttachServicesRoutes from './config-attach-services.js';
import configDiscountRoutes from './config-discounts.js';
import configFreeDaysRoutes from './config-free-days.js';
import configDayLevelRoutes from './config-day-level.js';
import configMinValueRoutes from './config-min-value.js';
import dtOrderRoutes from './dt-order.js';
import jobGateRoutes from "./job-gate.js";
import jobQuantityCheckRoutes from "./job-quantity-check.js";
import jobStockRoutes from "./job-stock.js";
import dtPkgStockRoutes from "./dt-package-stock.js";
import dtPalletStockRoutes from "./dt-pallet-stock.js";
import invVATRoutes from "./inv-vat.js";
import receiptsRoutes from "./receipts.js";
import reportsRoutes from "./reports.js";
import exeSupervisionRoutes from "./executive-supervision.js";
import apiTosRoutes from "./api-tos.js";

export default class Routes {
  constructor(app) {
    app.use("/api", homeRoutes);
    app.use("/api/tutorials", tutorialRoutes);
    app.use("/sa-user", userRoutes);
    app.use("/sa-menus", menuRoutes);
    app.use("/bs-item-types", itemTypeRoutes);
    app.use("/overview", capacityRoutes);
    app.use("/bs-warehouse", wareHouseRoutes);
    app.use("/bs-blocks", blockRoutes);
    app.use("/bs-gates", gateRoutes);
    app.use("/bs-equipments-types", equipmentTypeRoutes);
    app.use("/bs-equipments", equipmentRoutes);
    app.use("/bs-method", methodRoutes);
    app.use("/bs-units", unitRoutes);
    app.use("/bs-contracts", contractRoutes);
    app.use("/bs-contract-blocks", contractBlockRoutes);
    app.use("/bs-customer", customerRoutes);
    app.use("/bs-customer-type", customerTypeRoutes);
    app.use("/bs-trucks", truckRoutes);
    app.use("/bs-romooc", romoocRoutes);
    app.use("/dt-vessel-visits", vesselVisitRoutes);
    app.use("/dt-cntr-mnf-ld", maniFestCNTRRoutes);
    app.use("/dt-cntr-stocks", cntrStockRoutes);
    app.use("/dt-package-mnf-ld", pkgManifestladingRoutes);
    app.use("/trf-codes", tfrCodeRoutes);
    app.use("/trf-stds", tfrStdRoutes);
    app.use("/accounts", accountRoutes);
    app.use("/currency-type", currentTypeRoutes);
    app.use("/config-attach-services", configAttachServicesRoutes);
    app.use("/config-discounts", configDiscountRoutes);
    app.use("/config-free-days", configFreeDaysRoutes);
    app.use("/config-day-level", configDayLevelRoutes);
    app.use("/config-min-value", configMinValueRoutes);
    app.use("/dt-order", dtOrderRoutes);
    app.use("/job-gate", jobGateRoutes);
    app.use("/job-quantity-check", jobQuantityCheckRoutes);
    app.use("/job-stock", jobStockRoutes);
    app.use("/dt-package-stock", dtPkgStockRoutes);
    app.use("/dt-pallet-stock", dtPalletStockRoutes);
    app.use("/inv-vat", invVATRoutes);
    app.use("/receipts", receiptsRoutes);
    app.use("/reports", reportsRoutes);
    app.use("/executive-supervision", exeSupervisionRoutes);
    app.use("/api-tos", apiTosRoutes);
  }
}
